version: '3.8'

services:
  report-xplain-be:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=reportdb
      - DB_HOST=db
      - DB_PORT=5432
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BUCKET_NAME=report-uploads
    depends_on:
      - db
      - minio
    command: npm run start:dev

  report:
    build: ./frontend
    ports:
      - "80:4200"
    depends_on:
      - db
      - report-xplain-be
  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reportdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
